version: '3.8'
services:
  supabase-db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: postgres
      POSTGRES_DB: vector_store
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data: 